### ISSUE TITLE
Can not use txs/encode

### ISSUE THREAD

**Issue by Wangmmx** [bandprotocol/cosmoscan#125]
Is there any rest api to encode Tx and broadcast tx? I need to use only rest api, I can use txs/encode before on guanyu mainnet, but now it dosen't work

**Comment by evilpeach** [comment]
You can use `BandChai.js` to do that.
Here is a [documentation](https://docs.bandchain.org)

**Comment by Wangmmx** [comment]
> You can use `BandChain.js` to do that. Here is a [documentation](https://docs.bandchain.org)

Thanks for you reply, but I need to use lcd/rest api only, since I started test the band transfer 2 months ago, and it works well all the time, I will change a lot code to use the BandChain.js, because  I create the tx body offline and do not use any lib. Are `/txs/encode` and `/txs`  deleted?

**Comment by evilpeach** [comment]
Yes, these have been deleted. [Reference](https://docs.cosmos.network/master/migrations/rest.html)

Currently, BandChain use Cosmos SDK v.0.44.2

**Comment by Wangmmx** [comment]
Thanks, but sadly, these two apis are really important. If they are not there, the code will all be rewritten. Others who use the cosmos-sdk 0.44.2 also continue to use these two apis. I don’t understand why they are deleted. 

If there is no such interface, how can I calculate txHash in advance?

**Comment by evilpeach** [comment]
I've seen you asked these in Band's Discord. Let's talk in there.
