### ISSUE TITLE
Missing number of tokens (details of validators) 

### ISSUE THREAD

**Issue by AC-Validator** [bandprotocol/cosmoscan#33]
With the recent restyling, the detail of the tokens is no longer visible

![immagine](https://user-images.githubusercontent.com/11424273/122223328-5b3b1a80-ceb3-11eb-9770-53de647bf0e9.png)

**Comment by evilpeach** [comment]
I'll get it back.

**Comment by evilpeach** [comment]
Already made it. I'll deploy to production soon.
